const ENG2ARB = {
    "First Name":"الاسم الاول",
    "Middle Name":"اسم الاب",
    "Last Name":"الكنية",
    "Gender":"الجنس",
    "Birth Date":"تاريخ التولد",
    "Shoes Size":"مقاس الحذاء",
    "Waist Size":"مقاس الخصر",
    "Mother Name":"اسم الام",
    "Marital Status":"الحالة الاجتماعية",
    "Birth Place":"مكان الولادة",
    "Mobile":"الهاتف الخليوي",
    "Phone":"الهاتف الارضي",
    "Certigicate Type":"نوع الشهادة",
    "Certigicate Details":"تفاصيل الشهادة",
    "Engilsh Name":"الاسم بالانجيليزي",
    "Shoulders Size":"حجم الاكتاف",
    "":"",
    "":"",

};